name: pylint
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python${{ matrix.python-version }} -m pip install --upgrade pip setuptools wheel
          python${{ matrix.python-version }} -m pip install anthropic gTTS pydub requests SpeechRecognition
          python${{ matrix.python-version }} -m pip install pylint

      - name: Analysing the code with pylint
        run: |
          python${{ matrix.python-version }} -m pylint --disable C,W,no-error,design '*.py'
